// <copyright file="ApiTestBase.cs" company="APIMatic">
// SwaggerPetstoreOpenApi30.Tests
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using NUnit.Framework;
using SwaggerPetstoreOpenApi30.Standard;
using SwaggerPetstoreOpenApi30.Standard.Authentication;
using SwaggerPetstoreOpenApi30.Standard.Http.Client;
using SwaggerPetstoreOpenApi30.Standard.Models;

namespace SwaggerPetstoreOpenApi30.Tests
{
    /// <summary>
    /// ControllerTestBase Class.
    /// </summary>
    [TestFixture]
    public class ApiTestBase
    {
        /// <summary>
        /// Assert precision.
        /// </summary>
        protected const double AssertPrecision = 0.1;

        /// <summary>
        /// Gets HttpCallBackHandler.
        /// </summary>
        internal HttpCallback HttpCallBack { get; private set; } = new HttpCallback();

        /// <summary>
        /// Gets SwaggerPetstoreOpenApi30Client Client.
        /// </summary>
        protected SwaggerPetstoreOpenApi30Client Client { get; private set; }

        /// <summary>
        /// Set up the client.
        /// </summary>
        [OneTimeSetUp]
        public void SetUp()
        {
            SwaggerPetstoreOpenApi30Client config = SwaggerPetstoreOpenApi30Client.CreateFromEnvironment();
            this.Client = config.ToBuilder()
                .HttpCallback(HttpCallBack)
                .Build();
        }
    }
}