// <copyright file="PetApiTest.cs" company="APIMatic">
// SwaggerPetstoreOpenApi30.Tests
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Threading.Tasks;
using APIMatic.Core.Utilities;
using NUnit.Framework;
using Newtonsoft.Json.Converters;
using SwaggerPetstoreOpenApi30.Standard;
using SwaggerPetstoreOpenApi30.Standard.Apis;
using SwaggerPetstoreOpenApi30.Standard.Exceptions;
using SwaggerPetstoreOpenApi30.Standard.Http.Client;
using SwaggerPetstoreOpenApi30.Standard.Http.Response;
using SwaggerPetstoreOpenApi30.Standard.Utilities;

namespace SwaggerPetstoreOpenApi30.Tests
{
    /// <summary>
    /// PetApiTest.
    /// </summary>
    [TestFixture]
    public class PetApiTest : ApiTestBase
    {
        /// <summary>
        /// Controller instance (for all tests).
        /// </summary>
        private PetApi controller;

        /// <summary>
        /// Setup test class.
        /// </summary>
        [OneTimeSetUp]
        public void SetUpDerived()
        {
            this.controller = this.Client.PetApi;
        }

        /// <summary>
        /// Multiple status values can be provided with comma separated strings..
        /// </summary>
        /// <returns>A <see cref="Task"/> representing the asynchronous unit test.</returns>
        [Test]
        public async Task TestTestFindPetsByStatus()
        {
            // Parameters for the API call
            Standard.Models.PetStatus? status = null;

            // Perform API call
            ApiResponse<List<Standard.Models.Pet>> result = null;
            try
            {
                result = await this.controller.FindPetsByStatusAsync(status);
            }
            catch (ApiException)
            {
            }

            // Test response code
            Assert.AreEqual(200, HttpCallBack.Response.StatusCode, "Status should be 200");

            // Test headers
            Dictionary<string, string> headers = new Dictionary<string, string>();
            headers.Add("Content-Type", "application/json");

            Assert.IsTrue(
                    TestHelper.AreHeadersProperSubsetOf (
                    headers,
                    HttpCallBack.Response.Headers),
                    "Headers should match");
        }

        /// <summary>
        /// Multiple status values can be provided with comma separated strings..
        /// </summary>
        /// <returns>A <see cref="Task"/> representing the asynchronous unit test.</returns>
        [Test]
        public async Task TestTestFindPetsByStatus1()
        {
            // Parameters for the API call
            Standard.Models.PetStatus? status = null;

            // Perform API call
            ApiResponse<List<Standard.Models.Pet>> result = null;
            try
            {
                result = await this.controller.FindPetsByStatusAsync(status);
            }
            catch (ApiException)
            {
            }

            // Test response code
            Assert.AreEqual(200, HttpCallBack.Response.StatusCode, "Status should be 200");

            // Test headers
            Dictionary<string, string> headers = new Dictionary<string, string>();
            headers.Add("Content-Type", "application/xml");

            Assert.IsTrue(
                    TestHelper.AreHeadersProperSubsetOf (
                    headers,
                    HttpCallBack.Response.Headers),
                    "Headers should match");
        }

        /// <summary>
        /// Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing..
        /// </summary>
        /// <returns>A <see cref="Task"/> representing the asynchronous unit test.</returns>
        [Test]
        public async Task TestTestFindPetsByTags()
        {
            // Parameters for the API call
            List<string> tags = null;

            // Perform API call
            ApiResponse<List<Standard.Models.Pet>> result = null;
            try
            {
                result = await this.controller.FindPetsByTagsAsync(tags);
            }
            catch (ApiException)
            {
            }

            // Test response code
            Assert.AreEqual(200, HttpCallBack.Response.StatusCode, "Status should be 200");

            // Test headers
            Dictionary<string, string> headers = new Dictionary<string, string>();
            headers.Add("Content-Type", "application/json");

            Assert.IsTrue(
                    TestHelper.AreHeadersProperSubsetOf (
                    headers,
                    HttpCallBack.Response.Headers),
                    "Headers should match");
        }

        /// <summary>
        /// Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing..
        /// </summary>
        /// <returns>A <see cref="Task"/> representing the asynchronous unit test.</returns>
        [Test]
        public async Task TestTestFindPetsByTags1()
        {
            // Parameters for the API call
            List<string> tags = null;

            // Perform API call
            ApiResponse<List<Standard.Models.Pet>> result = null;
            try
            {
                result = await this.controller.FindPetsByTagsAsync(tags);
            }
            catch (ApiException)
            {
            }

            // Test response code
            Assert.AreEqual(200, HttpCallBack.Response.StatusCode, "Status should be 200");

            // Test headers
            Dictionary<string, string> headers = new Dictionary<string, string>();
            headers.Add("Content-Type", "application/xml");

            Assert.IsTrue(
                    TestHelper.AreHeadersProperSubsetOf (
                    headers,
                    HttpCallBack.Response.Headers),
                    "Headers should match");
        }

        /// <summary>
        /// Returns a single pet..
        /// </summary>
        /// <returns>A <see cref="Task"/> representing the asynchronous unit test.</returns>
        [Test]
        public async Task TestTestGetPetById()
        {
            // Parameters for the API call
            long petId = 10;

            // Perform API call
            ApiResponse<Standard.Models.Pet> result = null;
            try
            {
                result = await this.controller.GetPetByIdAsync(petId);
            }
            catch (ApiException)
            {
            }

            // Test response code
            Assert.AreEqual(200, HttpCallBack.Response.StatusCode, "Status should be 200");

            // Test headers
            Dictionary<string, string> headers = new Dictionary<string, string>();
            headers.Add("Content-Type", "application/json");

            Assert.IsTrue(
                    TestHelper.AreHeadersProperSubsetOf (
                    headers,
                    HttpCallBack.Response.Headers),
                    "Headers should match");
        }

        /// <summary>
        /// Returns a single pet..
        /// </summary>
        /// <returns>A <see cref="Task"/> representing the asynchronous unit test.</returns>
        [Test]
        public async Task TestTestGetPetById1()
        {
            // Parameters for the API call
            long petId = 10;

            // Perform API call
            ApiResponse<Standard.Models.Pet> result = null;
            try
            {
                result = await this.controller.GetPetByIdAsync(petId);
            }
            catch (ApiException)
            {
            }

            // Test response code
            Assert.AreEqual(200, HttpCallBack.Response.StatusCode, "Status should be 200");

            // Test headers
            Dictionary<string, string> headers = new Dictionary<string, string>();
            headers.Add("Content-Type", "application/xml");

            Assert.IsTrue(
                    TestHelper.AreHeadersProperSubsetOf (
                    headers,
                    HttpCallBack.Response.Headers),
                    "Headers should match");
        }

        /// <summary>
        /// Updates a pet resource based on the form data..
        /// </summary>
        /// <returns>A <see cref="Task"/> representing the asynchronous unit test.</returns>
        [Test]
        public async Task TestTestUpdatePetWithForm()
        {
            // Parameters for the API call
            long petId = 10;
            string name = null;
            string status = null;

            // Perform API call
            ApiResponse<Standard.Models.Pet> result = null;
            try
            {
                result = await this.controller.UpdatePetWithFormAsync(petId, name, status);
            }
            catch (ApiException)
            {
            }

            // Test response code
            Assert.AreEqual(200, HttpCallBack.Response.StatusCode, "Status should be 200");

            // Test headers
            Dictionary<string, string> headers = new Dictionary<string, string>();
            headers.Add("Content-Type", "application/json");

            Assert.IsTrue(
                    TestHelper.AreHeadersProperSubsetOf (
                    headers,
                    HttpCallBack.Response.Headers),
                    "Headers should match");
        }

        /// <summary>
        /// Updates a pet resource based on the form data..
        /// </summary>
        /// <returns>A <see cref="Task"/> representing the asynchronous unit test.</returns>
        [Test]
        public async Task TestTestUpdatePetWithForm1()
        {
            // Parameters for the API call
            long petId = 10;
            string name = null;
            string status = null;

            // Perform API call
            ApiResponse<Standard.Models.Pet> result = null;
            try
            {
                result = await this.controller.UpdatePetWithFormAsync(petId, name, status);
            }
            catch (ApiException)
            {
            }

            // Test response code
            Assert.AreEqual(200, HttpCallBack.Response.StatusCode, "Status should be 200");

            // Test headers
            Dictionary<string, string> headers = new Dictionary<string, string>();
            headers.Add("Content-Type", "application/xml");

            Assert.IsTrue(
                    TestHelper.AreHeadersProperSubsetOf (
                    headers,
                    HttpCallBack.Response.Headers),
                    "Headers should match");
        }

        /// <summary>
        /// Delete a pet..
        /// </summary>
        /// <returns>A <see cref="Task"/> representing the asynchronous unit test.</returns>
        [Test]
        public async Task TestTestDeletePet()
        {
            // Parameters for the API call
            long petId = 10;
            string apiKey = null;

            // Perform API call
            try
            {
                await this.controller.DeletePetAsync(petId, apiKey);
            }
            catch (ApiException)
            {
            }

            // Test response code
            Assert.AreEqual(200, HttpCallBack.Response.StatusCode, "Status should be 200");
        }

        /// <summary>
        /// Upload image of the pet..
        /// </summary>
        /// <returns>A <see cref="Task"/> representing the asynchronous unit test.</returns>
        [Test]
        public async Task TestTestUploadFile()
        {
            // Parameters for the API call
            long petId = 10;
            string additionalMetadata = null;
            FileStreamInfo body = null;

            // Perform API call
            ApiResponse<Standard.Models.ApiResponse> result = null;
            try
            {
                result = await this.controller.UploadFileAsync(petId, additionalMetadata, body);
            }
            catch (ApiException)
            {
            }

            // Test response code
            Assert.AreEqual(200, HttpCallBack.Response.StatusCode, "Status should be 200");

            // Test headers
            Dictionary<string, string> headers = new Dictionary<string, string>();
            headers.Add("Content-Type", "application/json");

            Assert.IsTrue(
                    TestHelper.AreHeadersProperSubsetOf (
                    headers,
                    HttpCallBack.Response.Headers),
                    "Headers should match");
        }
    }
}