// <copyright file="UserApiTest.cs" company="APIMatic">
// SwaggerPetstoreOpenApi30.Tests
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Threading.Tasks;
using APIMatic.Core.Utilities;
using NUnit.Framework;
using Newtonsoft.Json.Converters;
using SwaggerPetstoreOpenApi30.Standard;
using SwaggerPetstoreOpenApi30.Standard.Apis;
using SwaggerPetstoreOpenApi30.Standard.Exceptions;
using SwaggerPetstoreOpenApi30.Standard.Http.Client;
using SwaggerPetstoreOpenApi30.Standard.Http.Response;
using SwaggerPetstoreOpenApi30.Standard.Utilities;

namespace SwaggerPetstoreOpenApi30.Tests
{
    /// <summary>
    /// UserApiTest.
    /// </summary>
    [TestFixture]
    public class UserApiTest : ApiTestBase
    {
        /// <summary>
        /// Controller instance (for all tests).
        /// </summary>
        private UserApi controller;

        /// <summary>
        /// Setup test class.
        /// </summary>
        [OneTimeSetUp]
        public void SetUpDerived()
        {
            this.controller = this.Client.UserApi;
        }

        /// <summary>
        /// This can only be done by the logged in user..
        /// </summary>
        /// <returns>A <see cref="Task"/> representing the asynchronous unit test.</returns>
        [Test]
        public async Task TestTestCreateUser()
        {
            // Parameters for the API call
            long? id = 10;
            string username = "theUser";
            string firstName = "John";
            string lastName = "James";
            string email = "john@email.com";
            string password = "12345";
            string phone = "12345";
            int? userStatus = 1;

            // Perform API call
            ApiResponse<Standard.Models.User> result = null;
            try
            {
                result = await this.controller.CreateUserAsync(id, username, firstName, lastName, email, password, phone, userStatus);
            }
            catch (ApiException)
            {
            }

            // Test response code
            Assert.AreEqual(200, HttpCallBack.Response.StatusCode, "Status should be 200");

            // Test headers
            Dictionary<string, string> headers = new Dictionary<string, string>();
            headers.Add("Content-Type", "application/json");

            Assert.IsTrue(
                    TestHelper.AreHeadersProperSubsetOf (
                    headers,
                    HttpCallBack.Response.Headers),
                    "Headers should match");
        }

        /// <summary>
        /// This can only be done by the logged in user..
        /// </summary>
        /// <returns>A <see cref="Task"/> representing the asynchronous unit test.</returns>
        [Test]
        public async Task TestTestCreateUser1()
        {
            // Parameters for the API call
            long? id = 10;
            string username = "theUser";
            string firstName = "John";
            string lastName = "James";
            string email = "john@email.com";
            string password = "12345";
            string phone = "12345";
            int? userStatus = 1;

            // Perform API call
            ApiResponse<Standard.Models.User> result = null;
            try
            {
                result = await this.controller.CreateUserAsync(id, username, firstName, lastName, email, password, phone, userStatus);
            }
            catch (ApiException)
            {
            }

            // Test response code
            Assert.AreEqual(200, HttpCallBack.Response.StatusCode, "Status should be 200");

            // Test headers
            Dictionary<string, string> headers = new Dictionary<string, string>();
            headers.Add("Content-Type", "application/xml");

            Assert.IsTrue(
                    TestHelper.AreHeadersProperSubsetOf (
                    headers,
                    HttpCallBack.Response.Headers),
                    "Headers should match");
        }

        /// <summary>
        /// Creates list of users with given input array..
        /// </summary>
        /// <returns>A <see cref="Task"/> representing the asynchronous unit test.</returns>
        [Test]
        public async Task TestTestCreateUsersWithListInput()
        {
            // Parameters for the API call
            List<Standard.Models.User> body = null;

            // Perform API call
            ApiResponse<Standard.Models.User> result = null;
            try
            {
                result = await this.controller.CreateUsersWithListInputAsync(body);
            }
            catch (ApiException)
            {
            }

            // Test response code
            Assert.AreEqual(200, HttpCallBack.Response.StatusCode, "Status should be 200");

            // Test headers
            Dictionary<string, string> headers = new Dictionary<string, string>();
            headers.Add("Content-Type", "application/json");

            Assert.IsTrue(
                    TestHelper.AreHeadersProperSubsetOf (
                    headers,
                    HttpCallBack.Response.Headers),
                    "Headers should match");
        }

        /// <summary>
        /// Creates list of users with given input array..
        /// </summary>
        /// <returns>A <see cref="Task"/> representing the asynchronous unit test.</returns>
        [Test]
        public async Task TestTestCreateUsersWithListInput1()
        {
            // Parameters for the API call
            List<Standard.Models.User> body = null;

            // Perform API call
            ApiResponse<Standard.Models.User> result = null;
            try
            {
                result = await this.controller.CreateUsersWithListInputAsync(body);
            }
            catch (ApiException)
            {
            }

            // Test response code
            Assert.AreEqual(200, HttpCallBack.Response.StatusCode, "Status should be 200");

            // Test headers
            Dictionary<string, string> headers = new Dictionary<string, string>();
            headers.Add("Content-Type", "application/xml");

            Assert.IsTrue(
                    TestHelper.AreHeadersProperSubsetOf (
                    headers,
                    HttpCallBack.Response.Headers),
                    "Headers should match");
        }

        /// <summary>
        /// Log into the system..
        /// </summary>
        /// <returns>A <see cref="Task"/> representing the asynchronous unit test.</returns>
        [Test]
        public async Task TestTestLoginUser()
        {
            // Parameters for the API call
            string username = null;
            string password = null;

            // Perform API call
            ApiResponse<string> result = null;
            try
            {
                result = await this.controller.LoginUserAsync(username, password);
            }
            catch (ApiException)
            {
            }

            // Test response code
            Assert.AreEqual(200, HttpCallBack.Response.StatusCode, "Status should be 200");

            // Test headers
            Dictionary<string, string> headers = new Dictionary<string, string>();
            headers.Add("X-Rate-Limit", null);
            headers.Add("X-Expires-After", null);
            headers.Add("Content-Type", "application/xml");

            Assert.IsTrue(
                    TestHelper.AreHeadersProperSubsetOf (
                    headers,
                    HttpCallBack.Response.Headers),
                    "Headers should match");
        }

        /// <summary>
        /// Log into the system..
        /// </summary>
        /// <returns>A <see cref="Task"/> representing the asynchronous unit test.</returns>
        [Test]
        public async Task TestTestLoginUser1()
        {
            // Parameters for the API call
            string username = null;
            string password = null;

            // Perform API call
            ApiResponse<string> result = null;
            try
            {
                result = await this.controller.LoginUserAsync(username, password);
            }
            catch (ApiException)
            {
            }

            // Test response code
            Assert.AreEqual(200, HttpCallBack.Response.StatusCode, "Status should be 200");

            // Test headers
            Dictionary<string, string> headers = new Dictionary<string, string>();
            headers.Add("X-Rate-Limit", null);
            headers.Add("X-Expires-After", null);
            headers.Add("Content-Type", "application/json");

            Assert.IsTrue(
                    TestHelper.AreHeadersProperSubsetOf (
                    headers,
                    HttpCallBack.Response.Headers),
                    "Headers should match");
        }

        /// <summary>
        /// Log user out of the system..
        /// </summary>
        /// <returns>A <see cref="Task"/> representing the asynchronous unit test.</returns>
        [Test]
        public async Task TestTestLogoutUser()
        {
            // Perform API call
            try
            {
                await this.controller.LogoutUserAsync();
            }
            catch (ApiException)
            {
            }

            // Test response code
            Assert.AreEqual(200, HttpCallBack.Response.StatusCode, "Status should be 200");
        }
    }
}